/*
 * @Descripttion:
 * @Author: yft
 * @Date: 2022-08-29 17:19:00
 * @LastEditors: yft
 * @LastEditTime: 2022-08-29 17:19:44
 */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
		UsePinia: typeof import('./../components/usePinia.vue')['default']
		VueUse: typeof import('./../components/vueUse.vue')['default']
	}
}
