/*
 * @Descripttion:
 * @Author: yft
 * @Date: 2022-08-29 17:19:00
 * @LastEditors: yft
 * @LastEditTime: 2022-11-15 17:02:19
 */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		ElAside: typeof import('element-plus/es')['ElAside']
		ElButton: typeof import('element-plus/es')['ElButton']
		ElContainer: typeof import('element-plus/es')['ElContainer']
		ElIcon: typeof import('element-plus/es')['ElIcon']
		ElMenu: typeof import('element-plus/es')['ElMenu']
		ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
		ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
		ElPopover: typeof import('element-plus/es')['ElPopover']
		ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
		ElTag: typeof import('element-plus/es')['ElTag']
		Footer: typeof import('./../layout/Footer.vue')['default']
		Header: typeof import('./../layout/Header.vue')['default']
		HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
		Layout: typeof import('./../layout/Layout.vue')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
		SiderBar: typeof import('./../components/SiderBar.vue')['default']
		Table: typeof import('./../components/Table.vue')['default']
		UsePinia: typeof import('./../components/usePinia.vue')['default']
		VueUse: typeof import('./../components/vueUse.vue')['default']
	}
}
